-- HealthApp · curated staple foods (73 rows)
--
-- GENERATED by scripts/build-food-seed-sql.ts from apps/web/lib/demo-foods.ts.
-- Do not edit by hand; edit the TypeScript list and regenerate.
--
-- Paste into the Supabase dashboard → SQL Editor → Run. Requires one user with
-- role 'admin' (supabase/seed/accounts.sql creates it). Safe to re-run: rows
-- upsert on (source, external_id).

do $$
begin
  if not exists (select 1 from public.users where role = 'admin') then
    raise exception 'No admin user: run supabase/seed/accounts.sql first';
  end if;
end $$;

insert into public.foods
  (owner_id, source, external_id, name_en, name_ro, kcal_100g, protein_100g, carbs_100g, fat_100g, verified, portions)
values
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:chicken-breast', 'Chicken breast, raw', 'Piept de pui, crud', 165, 31, 0, 3.6, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:chicken-thigh', 'Chicken thigh, raw', 'Pulpă de pui, crudă', 209, 26, 0, 10.9, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:turkey-breast', 'Turkey breast', 'Piept de curcan', 135, 30, 0, 1, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:beef-mince-10', 'Beef mince 10%', 'Carne tocată de vită 10%', 176, 20, 0, 10, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:pork-loin', 'Pork loin', 'Mușchi de porc', 143, 21, 0, 6, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:salmon', 'Salmon', 'Somon', 208, 20, 0, 13, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:cod', 'Cod', 'Cod', 82, 18, 0, 0.7, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:tuna-can', 'Tuna in water, canned', 'Ton în apă, conservă', 116, 26, 0, 1, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:egg', 'Egg, whole', 'Ou întreg', 143, 12.6, 0.7, 9.5, true, '[{"label":"S","grams":44,"note":"small, under 53 g with shell","origin":"curated"},{"label":"M","grams":50,"note":"medium, 53-63 g with shell","origin":"curated"},{"label":"L","grams":58,"note":"large, 63-73 g with shell","origin":"curated"},{"label":"XL","grams":66,"note":"very large, over 73 g with shell","origin":"curated"}]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:egg-white', 'Egg white', 'Albuș de ou', 52, 11, 0.7, 0.2, true, '[{"label":"S","grams":28,"note":"white of a small egg","origin":"curated"},{"label":"M","grams":33,"note":"white of a medium egg","origin":"curated"},{"label":"L","grams":38,"note":"white of a large egg","origin":"curated"}]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:whey', 'Whey isolate', 'Proteină din zer izolat', 370, 85, 4, 1.5, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:greek-yogurt', 'Greek yogurt 2%', 'Iaurt grecesc 2%', 73, 10, 3.6, 2, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:cottage-cheese', 'Cottage cheese', 'Brânză de vaci', 98, 11, 3.4, 4.3, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:telemea', 'Telemea cheese', 'Telemea', 260, 17, 1, 21, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:milk-15', 'Milk 1.5%', 'Lapte 1,5%', 47, 3.4, 4.8, 1.5, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:kefir', 'Kefir', 'Chefir', 55, 3.3, 4.5, 2.5, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:oats', 'Oats', 'Fulgi de ovăz', 389, 16.9, 66.3, 6.9, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:rice-cooked', 'Rice, cooked', 'Orez fiert', 130, 2.7, 28, 0.3, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:rice-raw', 'Rice, raw', 'Orez crud', 360, 7, 79, 0.6, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:pasta-cooked', 'Pasta, cooked', 'Paste fierte', 158, 5.8, 31, 0.9, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:potato', 'Potatoes', 'Cartofi', 77, 2, 17, 0.1, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:sweet-potato', 'Sweet potato', 'Cartof dulce', 86, 1.6, 20, 0.1, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:bread-wholegrain', 'Wholegrain bread', 'Pâine integrală', 247, 13, 41, 3.4, true, '[{"label":"1 slice","grams":35,"note":"standard sandwich slice","origin":"curated"},{"label":"2 slices","grams":70,"note":"two standard slices","origin":"curated"}]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:polenta', 'Polenta, cooked', 'Mămăligă', 85, 2, 18, 0.4, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:buckwheat', 'Buckwheat, cooked', 'Hrișcă fiartă', 92, 3.4, 20, 0.6, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:quinoa', 'Quinoa, cooked', 'Quinoa fiartă', 120, 4.4, 21, 1.9, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:lentils', 'Lentils, cooked', 'Linte fiartă', 116, 9, 20, 0.4, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:chickpeas', 'Chickpeas, cooked', 'Năut fiert', 164, 8.9, 27, 2.6, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:beans-white', 'White beans, cooked', 'Fasole albă fiartă', 139, 9.7, 25, 0.5, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:banana', 'Banana', 'Banană', 89, 1.1, 23, 0.3, true, '[{"label":"S","grams":90,"note":"small, peeled","origin":"curated"},{"label":"M","grams":118,"note":"medium, peeled","origin":"curated"},{"label":"L","grams":136,"note":"large, peeled","origin":"curated"}]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:apple', 'Apple', 'Măr', 52, 0.3, 14, 0.2, true, '[{"label":"S","grams":105,"note":"small, cored","origin":"curated"},{"label":"M","grams":138,"note":"medium, cored","origin":"curated"},{"label":"L","grams":172,"note":"large, cored","origin":"curated"}]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:blueberries', 'Blueberries', 'Afine', 57, 0.7, 14.5, 0.3, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:strawberries', 'Strawberries', 'Căpșuni', 32, 0.7, 7.7, 0.3, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:orange', 'Orange', 'Portocală', 47, 0.9, 12, 0.1, true, '[{"label":"S","grams":96,"note":"small, peeled","origin":"curated"},{"label":"M","grams":131,"note":"medium, peeled","origin":"curated"},{"label":"L","grams":184,"note":"large, peeled","origin":"curated"}]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:grapes', 'Grapes', 'Struguri', 69, 0.7, 18, 0.2, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:broccoli', 'Broccoli', 'Broccoli', 34, 2.8, 7, 0.4, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:spinach', 'Spinach', 'Spanac', 23, 2.9, 3.6, 0.4, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:tomato', 'Tomato', 'Roșie', 18, 0.9, 3.9, 0.2, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:cucumber', 'Cucumber', 'Castravete', 15, 0.7, 3.6, 0.1, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:bell-pepper', 'Bell pepper', 'Ardei gras', 31, 1, 6, 0.3, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:carrot', 'Carrot', 'Morcov', 41, 0.9, 10, 0.2, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:onion', 'Onion', 'Ceapă', 40, 1.1, 9.3, 0.1, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:zucchini', 'Zucchini', 'Dovlecel', 17, 1.2, 3.1, 0.3, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:mixed-salad', 'Mixed salad', 'Salată mixtă', 17, 1.4, 2.9, 0.2, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:cabbage', 'Cabbage, raw', 'Varză', 25, 1.3, 5.8, 0.1, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:cauliflower', 'Cauliflower, raw', 'Conopidă', 25, 1.9, 5, 0.3, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:green-beans', 'Green beans, raw', 'Fasole verde', 31, 1.8, 7, 0.2, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:peas', 'Peas, green, raw', 'Mazăre verde', 81, 5.4, 14.4, 0.4, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:mushrooms', 'Mushrooms, white, raw', 'Ciuperci albe', 22, 3.1, 3.3, 0.3, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:beetroot', 'Beetroot, raw', 'Sfeclă roșie', 43, 1.6, 9.6, 0.2, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:aubergine', 'Aubergine, raw', 'Vinete', 25, 1, 5.9, 0.2, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:sweetcorn', 'Sweetcorn, raw', 'Porumb dulce', 86, 3.3, 18.7, 1.4, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:lettuce', 'Lettuce, green leaf', 'Salată verde', 15, 1.4, 2.9, 0.2, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:garlic', 'Garlic, raw', 'Usturoi', 149, 6.4, 33.1, 0.5, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:pear', 'Pear, raw', 'Pară', 57, 0.4, 15.2, 0.1, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:peach', 'Peach, raw', 'Piersică', 39, 0.9, 9.5, 0.3, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:watermelon', 'Watermelon, raw', 'Pepene roșu', 30, 0.6, 7.6, 0.2, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:cherries', 'Cherries, sweet, raw', 'Cireșe', 63, 1.1, 16, 0.2, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:yogurt-plain', 'Plain yogurt, whole milk', 'Iaurt simplu 3,5%', 61, 3.5, 4.7, 3.3, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:cascaval', 'Semi-hard cheese (gouda type)', 'Cașcaval (tip gouda)', 356, 24.9, 2.2, 27.4, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:sour-cream', 'Sour cream, cultured', 'Smântână 20%', 198, 2.4, 4.6, 19.4, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:chicken-ham', 'Chicken breast, deli sliced', 'Șuncă de pui (piept feliat)', 98, 17.4, 2.9, 1.9, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:tofu', 'Tofu, firm', 'Tofu ferm', 144, 17.3, 2.8, 8.7, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:sunflower-seeds', 'Sunflower seeds, kernels', 'Semințe de floarea-soarelui', 584, 20.8, 20, 51.5, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:dark-chocolate', 'Dark chocolate 70-85%', 'Ciocolată neagră 70%', 598, 7.8, 45.9, 42.6, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:honey', 'Honey', 'Miere', 304, 0.3, 82.4, 0, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:olive-oil', 'Olive oil', 'Ulei de măsline', 884, 0, 0, 100, true, '[{"label":"1 tsp","grams":5,"note":"level teaspoon","origin":"curated"},{"label":"1 tbsp","grams":14,"note":"level tablespoon","origin":"curated"}]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:sunflower-oil', 'Sunflower oil', 'Ulei de floarea-soarelui', 884, 0, 0, 100, true, '[{"label":"1 tsp","grams":5,"note":"level teaspoon","origin":"curated"},{"label":"1 tbsp","grams":14,"note":"level tablespoon","origin":"curated"}]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:butter', 'Butter', 'Unt', 717, 0.9, 0.1, 81, true, '[{"label":"1 tsp","grams":5,"note":"level teaspoon","origin":"curated"},{"label":"1 tbsp","grams":14,"note":"level tablespoon","origin":"curated"}]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:almonds', 'Almonds', 'Migdale', 579, 21, 22, 50, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:walnuts', 'Walnuts', 'Nuci', 654, 15, 14, 65, true, '[]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:peanut-butter', 'Peanut butter', 'Unt de arahide', 588, 25, 20, 50, true, '[{"label":"1 tsp","grams":6,"note":"level teaspoon","origin":"curated"},{"label":"1 tbsp","grams":16,"note":"level tablespoon","origin":"curated"}]'::jsonb),
  ((select id from public.users where role = 'admin' order by created_at limit 1), 'custom', 'curated:avocado', 'Avocado', 'Avocado', 160, 2, 8.5, 15, true, '[{"label":"half","grams":100,"note":"half a medium avocado","origin":"curated"},{"label":"whole","grams":200,"note":"one medium avocado","origin":"curated"}]'::jsonb)
on conflict (source, external_id) do update set
  name_en = excluded.name_en,
  name_ro = excluded.name_ro,
  kcal_100g = excluded.kcal_100g,
  protein_100g = excluded.protein_100g,
  carbs_100g = excluded.carbs_100g,
  fat_100g = excluded.fat_100g,
  verified = excluded.verified,
  portions = excluded.portions;
