// Turns the curated staples in apps/web/lib/demo-foods.ts into
// supabase/seed/foods.sql.
//
// Open Food Facts is a database of packaged products. It has no "cabbage" or
// "chicken breast", and its Romanian coverage is thin, so a live install starts
// with an empty search box for exactly the foods a meal plan is built from.
// These rows fill that gap: the same staples demo mode ships with, Romanian
// names included, stored as verified rows owned by the admin account so that
// every signed-in user can read them and only the admin can edit them.
//
// Idempotent: upserts on (source, external_id) with external_id "curated:<id>".
//
//   npx vite-node scripts/build-food-seed-sql.ts

import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { demoFoods, portionsFor } from "../apps/web/lib/demo-foods";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const output = path.join(root, "supabase/seed/foods.sql");

function lit(value: string | number | null | undefined): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "number") return String(value);
  return `'${value.replace(/'/g, "''")}'`;
}

const rows = demoFoods.map((food) => {
  // Curated servings, in the shape foods_portions_shape checks. Labels are
  // already short ("M", "1 slice"); the constraint caps them at 16 chars.
  const portions = portionsFor(food).map((p) => ({
    label: p.label,
    grams: p.grams,
    note: p.note,
    origin: "curated",
  }));
  return [
    "(select id from public.users where role = 'admin' order by created_at limit 1)",
    lit("custom"),
    lit(`curated:${food.id}`),
    lit(food.name_en),
    lit(food.name_ro),
    lit(food.per_100g.kcal),
    lit(food.per_100g.protein),
    lit(food.per_100g.carbs),
    lit(food.per_100g.fat),
    "true",
    `${lit(JSON.stringify(portions))}::jsonb`,
  ].join(", ");
});

const sql = `-- HealthApp · curated staple foods (${rows.length} rows)
--
-- GENERATED by scripts/build-food-seed-sql.ts from apps/web/lib/demo-foods.ts.
-- Do not edit by hand; edit the TypeScript list and regenerate.
--
-- Paste into the Supabase dashboard → SQL Editor → Run. Requires one user with
-- role 'admin' (supabase/seed/accounts.sql creates it). Safe to re-run: rows
-- upsert on (source, external_id).

do $$
begin
  if not exists (select 1 from public.users where role = 'admin') then
    raise exception 'No admin user: run supabase/seed/accounts.sql first';
  end if;
end $$;

insert into public.foods
  (owner_id, source, external_id, name_en, name_ro, kcal_100g, protein_100g, carbs_100g, fat_100g, verified, portions)
values
${rows.map((r) => `  (${r})`).join(",\n")}
on conflict (source, external_id) do update set
  name_en = excluded.name_en,
  name_ro = excluded.name_ro,
  kcal_100g = excluded.kcal_100g,
  protein_100g = excluded.protein_100g,
  carbs_100g = excluded.carbs_100g,
  fat_100g = excluded.fat_100g,
  verified = excluded.verified,
  portions = excluded.portions;
`;

writeFileSync(output, sql, "utf8");
console.log(`wrote ${path.relative(root, output)}: ${rows.length} rows`);
